In [1]:
import pandas as pd
import pymongo
from pymongo import MongoClient
pd.options.display.max_columns = None
client = MongoClient()

In [3]:
ironhack = client['ironhack']
sandwich = ironhack.sandwich

In [5]:
houses = pd.DataFrame(sandwich.find())
houses.head(5)

,_id,,index,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,62077501659efd3d6b074e74,0,0,ORD182494,ID6197211592,2019-06-22,Thompson,"[('Lucent 330S', 1), ('Thunder line', 2), ('iS...",12200,79.89,-37.8151052,144.9328434,10,11059.89,Winter,True,1.28,perfect phone and trusted seller. phone itself...,True
1,62077501659efd3d6b074e75,1,1,ORD395518,ID0282825849,2019-12-29,Thompson,"[('Thunder line', 1), ('Universe Note', 2)]",9080,62.71,-37.8027362,144.9511178,0,9142.71,Summer,False,1.1621,it keeps dropping calls the wifi don't work th...,False
2,62077501659efd3d6b074e76,2,2,ORD494479,ID0579391891,2019-03-02,Nickolson,"[('Thunder line', 1), ('pearTV', 2)]",10670,65.87,-37.8213016,144.9575809,10,9668.87,Autumn,False,1.0949,five stars this is a great cheap phone.,True
3,62077501659efd3d6b074e77,3,3,ORD019224,ID4544561904,2019-01-12,Nickolson,"[('Universe Note', 1), ('Alcon 10', 2), ('Oliv...",24800,57.61,-37.8114157,144.9730729,15,21137.61,Summer,False,0.8571,charger did not fit the charger didn't fit.,False
4,62077501659efd3d6b074e78,4,4,ORD104032,ID6231506320,2019-11-28,Nickolson,"[('Universe Note', 1), ('Olivia x460', 1), ('i...",9145,75.54,37.8238586,144.9698923,25,6934.29,Spring,False,0.5867,four stars good,True

In [9]:
houses.shape # 19 columnas, 658 filas
houses.size # 12502 datos
pd.isna(houses).sum() # No hay nulos
houses.dtypes

_id                              object
                                 object
index                            object
order_id                         object
customer_id                      object
date                             object
nearest_warehouse                object
shopping_cart                    object
order_price                      object
delivery_charges                 object
customer_lat                     object
customer_long                    object
coupon_discount                  object
order_total                      object
season                           object
is_expedited_delivery            object
distance_to_nearest_warehouse    object
latest_customer_review           object
is_happy_customer                object
dtype: object

In [ ]:
columnas_float = [delivery_charges	customer_lat	customer_long distance_to_nearest_warehouse]